Upgrade vendored bats version to 0.4.0.
Closes #12

diff --git a/vendor/bats/libexec/bats-exec-test b/vendor/bats/libexec/bats-exec-test
--- a/vendor/bats/libexec/bats-exec-test
+++ b/vendor/bats/libexec/bats-exec-test
@@ -30,13 +30,21 @@ BATS_TEST_DIRNAME="$(dirname "$BATS_TEST_FILENAME")"
 BATS_TEST_NAMES=()
 
 load() {
-  local filename="$BATS_TEST_DIRNAME/$1.bash"
+  local name="$1"
+  local filename
+
+  if [ "${name:0:1}" = "/" ]; then
+    filename="${name}"
+  else
+    filename="$BATS_TEST_DIRNAME/${name}.bash"
+  fi
+
   [ -f "$filename" ] || {
     echo "bats: $filename does not exist" >&2
     exit 1
   }
 
-  source "$BATS_TEST_DIRNAME/$1.bash"
+  source "${filename}"
 }
 
 run() {
@@ -82,20 +90,150 @@ bats_test_function() {
   BATS_TEST_NAMES["${#BATS_TEST_NAMES[@]}"]="$test_name"
 }
 
+bats_capture_stack_trace() {
+  BATS_PREVIOUS_STACK_TRACE=( "${BATS_CURRENT_STACK_TRACE[@]}" )
+  BATS_CURRENT_STACK_TRACE=()
+
+  local test_pattern=" $BATS_TEST_NAME $BATS_TEST_SOURCE"
+  local setup_pattern=" setup $BATS_TEST_SOURCE"
+  local teardown_pattern=" teardown $BATS_TEST_SOURCE"
+
+  local frame
+  local index=1
+
+  while frame="$(caller "$index")"; do
+    BATS_CURRENT_STACK_TRACE["${#BATS_CURRENT_STACK_TRACE[@]}"]="$frame"
+    if [[ "$frame" = *"$test_pattern"     || \
+          "$frame" = *"$setup_pattern"    || \
+          "$frame" = *"$teardown_pattern" ]]; then
+      break
+    else
+      let index+=1
+    fi
+  done
+
+  BATS_SOURCE="$(bats_frame_filename "${BATS_CURRENT_STACK_TRACE[0]}")"
+  BATS_LINENO="$(bats_frame_lineno "${BATS_CURRENT_STACK_TRACE[0]}")"
+}
+
+bats_print_stack_trace() {
+  local frame
+  local index=1
+  local count="${#@}"
+
+  for frame in "$@"; do
+    local filename="$(bats_trim_filename "$(bats_frame_filename "$frame")")"
+    local lineno="$(bats_frame_lineno "$frame")"
+
+    if [ $index -eq 1 ]; then
+      echo -n "# ("
+    else
+      echo -n "#  "
+    fi
+
+    local fn="$(bats_frame_function "$frame")"
+    if [ "$fn" != "$BATS_TEST_NAME" ]; then
+      echo -n "from function \`$fn' "
+    fi
+
+    if [ $index -eq $count ]; then
+      echo "in test file $filename, line $lineno)"
+    else
+      echo "in file $filename, line $lineno,"
+    fi
+
+    let index+=1
+  done
+}
+
+bats_print_failed_command() {
+  local frame="$1"
+  local status="$2"
+  local filename="$(bats_frame_filename "$frame")"
+  local lineno="$(bats_frame_lineno "$frame")"
+
+  local failed_line="$(bats_extract_line "$filename" "$lineno")"
+  local failed_command="$(bats_strip_string "$failed_line")"
+  echo -n "#   \`${failed_command}' "
+
+  if [ $status -eq 1 ]; then
+    echo "failed"
+  else
+    echo "failed with status $status"
+  fi
+}
+
+bats_frame_lineno() {
+  local frame="$1"
+  local lineno="${frame%% *}"
+  echo "$lineno"
+}
+
+bats_frame_function() {
+  local frame="$1"
+  local rest="${frame#* }"
+  local fn="${rest%% *}"
+  echo "$fn"
+}
+
+bats_frame_filename() {
+  local frame="$1"
+  local rest="${frame#* }"
+  local filename="${rest#* }"
+
+  if [ "$filename" = "$BATS_TEST_SOURCE" ]; then
+    echo "$BATS_TEST_FILENAME"
+  else
+    echo "$filename"
+  fi
+}
+
+bats_extract_line() {
+  local filename="$1"
+  local lineno="$2"
+  sed -n "${lineno}p" "$filename"
+}
+
+bats_strip_string() {
+  local string="$1"
+  printf "%s" "$string" | sed -e "s/^[ "$'\t'"]*//" -e "s/[ "$'\t'"]*$//"
+}
+
+bats_trim_filename() {
+  local filename="$1"
+  local length="${#BATS_CWD}"
+
+  if [ "${filename:0:length+1}" = "${BATS_CWD}/" ]; then
+    echo "${filename:length+1}"
+  else
+    echo "$filename"
+  fi
+}
+
 bats_debug_trap() {
   if [ "$BASH_SOURCE" != "$1" ]; then
-    BATS_LINE_NUMBER="$BATS_LINE_NUMBER_"
-    BATS_LINE_NUMBER_="$2"
+    bats_capture_stack_trace
   fi
 }
 
 bats_error_trap() {
+  BATS_ERROR_STATUS="$?"
+  BATS_ERROR_STACK_TRACE=( "${BATS_PREVIOUS_STACK_TRACE[@]}" )
   trap - debug
 }
 
 bats_teardown_trap() {
-  trap bats_exit_trap exit
-  teardown >>"$BATS_OUT" 2>&1
+  trap "bats_exit_trap" exit
+  local status=0
+  teardown >>"$BATS_OUT" 2>&1 || status="$?"
+
+  if [ $status -eq 0 ]; then
+    BATS_TEARDOWN_COMPLETED=1
+  elif [ -n "$BATS_TEST_COMPLETED" ]; then
+    BATS_ERROR_STATUS="$status"
+    BATS_ERROR_STACK_TRACE=( "${BATS_CURRENT_STACK_TRACE[@]}" )
+  fi
+
   bats_exit_trap
 }
 
@@ -112,9 +250,10 @@ bats_exit_trap() {
     fi
   fi
 
-  if [ -z "$BATS_TEST_COMPLETED" ]; then
+  if [ -z "$BATS_TEST_COMPLETED" ] || [ -z "$BATS_TEARDOWN_COMPLETED" ]; then
     echo "not ok $BATS_TEST_NUMBER $BATS_TEST_DESCRIPTION" >&3
-    echo "# (in test file $BATS_TEST_FILENAME, line $BATS_LINE_NUMBER)" >&3
+    bats_print_stack_trace "${BATS_ERROR_STACK_TRACE[@]}" >&3
+    bats_print_failed_command "${BATS_ERROR_STACK_TRACE[${#BATS_ERROR_STACK_TRACE[@]}-1]}" "$BATS_ERROR_STATUS" >&3
     sed -e "s/^/# /" < "$BATS_OUT" >&3
     status=1
   else
@@ -132,7 +271,7 @@ bats_perform_tests() {
   status=0
   for test_name in "$@"; do
     "$0" $BATS_EXTENDED_SYNTAX "$BATS_TEST_FILENAME" "$test_name" "$test_number" || status=1
-    test_number=$(($test_number + 1))
+    let test_number+=1
   done
   exit "$status"
 }
@@ -147,8 +286,8 @@ bats_perform_test() {
     fi
 
     BATS_TEST_COMPLETED=""
-    BATS_ERROR_LINE=""
-    trap "bats_debug_trap \"\$BASH_SOURCE\" \$LINENO" debug
+    BATS_TEARDOWN_COMPLETED=""
+    trap "bats_debug_trap \"\$BASH_SOURCE\"" debug
     trap "bats_error_trap" err
     trap "bats_teardown_trap" exit
     "$BATS_TEST_NAME" >>"$BATS_OUT" 2>&1
@@ -173,7 +312,7 @@ BATS_OUT="${BATS_TMPNAME}.out"
 bats_preprocess_source() {
   BATS_TEST_SOURCE="${BATS_TMPNAME}.src"
   { tr -d '\r' < "$BATS_TEST_FILENAME"; echo; } | bats-preprocess > "$BATS_TEST_SOURCE"
-  trap bats_cleanup_preprocessed_source err exit
+  trap "bats_cleanup_preprocessed_source" err exit
   trap "bats_cleanup_preprocessed_source; exit 1" int
 }
 
